name: Generate GitHub Metrics SVG

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Profile details card
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/base.svg
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai

      - name: Language indepth
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_affiliations: owner, collaborator, organization_member
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, jupyter notebook
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_analysis_timeout: 15

      - name: Full-year isocalendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Activity view
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

      - name: Coding habits
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Asia/Shanghai

      - name: Notable contributions
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/notable.svg
          base: ""
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all

      - name: Stars
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/stars.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 10

      - name: Full calendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrenalineY
          filename: github-metrics/calendar.full.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
